---
name: Porn Image Recognition
author: xc
description: Porn Image Recognition
topic: Porn Image Recognition
algorithm: ResNet
language: python3
virtualenv: flyai_env/bin/
framework: Keras

data:
  id: PornImageRecognition
  name: Porn Image Recognition
  category: image


model:
  processor: Processor
  input_x: input_x
  input_y: input_y
  output_y: output_y
  input:
    columns:
      - name: image_path
        type: string
    to_type: float
    to_shape: [224,224,3]
  output:
    columns:
      - name: label
        type: int
    to_type: int
    to_shape: [5]


evaluate:
  score: torch_accuracy

servers:
  - id: flyai
    url: https://flyai.com
...